### ISSUE TITLE
p.70 3.3 黒丸1の誤字

### ISSUE THREAD

**Issue by michilu** [oreilly-japan/concurrency-in-go-support#10]
ページ番号：70
セクション番号：3.3
内容タイトル：黒丸1の誤字
誤っている内容：❶ チャネルを閉じます。
正しい内容：❷ チャネルを閉じます。
その他コメント：下から2行目。PDF版のみ

**Comment by ymotongpoo** [comment]
@orj-takizawa PDF版だけ異なるということなのでビルドプロセスを確認頂けますか。

**Comment by orj-takizawa** [comment]
こちらは版面とPDFの作成に使用したツールの仕様に起因する問題です。ソース側を修正して同様の問題が起きないよう変更します。ご指摘ありがとうございます。
