### ISSUE TITLE
p.89 4.1 誤字の疑い

### ISSUE THREAD

**Issue by michilu** [oreilly-japan/concurrency-in-go-support#12]
ページ番号：89
セクション番号：4.1
内容タイトル：誤字の疑い
誤っている内容：拘束を矯正する
正しい内容：拘束を強制する
その他コメント：3行目。原文に寄るかと思いますが、念のため挙げます。

**Comment by ymotongpoo** [comment]
@michilu 報告ありがとうございます。原文は `enforce` なので誤字でした。errataに反映しました。
