### ISSUE TITLE
p.104 4.6 注釈5 誤字の疑い

### ISSUE THREAD

**Issue by michilu** [oreilly-japan/concurrency-in-go-support#13]
ページ番号：104
セクション番号：4.6
内容タイトル：注釈5
誤っている内容：具象化
正しい内容：
その他コメント：本文中では「具体化」と記述していますが、注釈内では「具象化」と記述があります。

**Comment by ymotongpoo** [comment]
@michilu 報告ありがとうございます。確認したところ訳語が不統一になっていました。「具体化」で統一し、errataに登録しました。
