### ISSUE TITLE
p.81 case分 → case文

### ISSUE THREAD

**Issue by hkdnet** [oreilly-japan/concurrency-in-go-support#15]
ページ番号：p.81
セクション番号：3.4 select 文
内容タイトル： case分 → case文
誤っている内容：
つまり、case 分全体では、それぞれの条件が等しく選択される可能性があるわけです。
正しい内容：
つまり、case 文全体では、それぞれの条件が等しく選択される可能性があるわけです。
その他コメント：

**Comment by ymotongpoo** [comment]
@hkdnet ご報告ありがとうございます。errataに登録しました。
