### ISSUE TITLE
p.104 セブセット → サブセット

### ISSUE THREAD

**Issue by hkdnet** [oreilly-japan/concurrency-in-go-support#16]
ページ番号：p.104
セクション番号：4.6 パイプライン
内容タイトル：セブセット → サブセット
誤っている内容：
モナドのセブセットと考えることもできます。
正しい内容：
モナドのサブセットと考えることもできます。
その他コメント：
google 検索の結果、固有名詞以外にも「セブセット」という表記を確認しています。同様の typo だと思っておりますが、誤記でなかったらすみません。

**Comment by ymotongpoo** [comment]
@hkdnet ご報告ありがとうございます。Google検索までしていただいて恐縮です。単純なtypoでした。errataに登録しました。
