### ISSUE TITLE
p.213 訳注に閉じカギカッコがない

### ISSUE THREAD

**Issue by hkdnet** [oreilly-japan/concurrency-in-go-support#17]
ページ番号：p.213
セクション番号：6.1 ワークスティーリング
内容タイトル：訳注に閉じカギカッコがない
誤っている内容：
この方式にはここには触れられていないメリットがあり、「スレッドプールにスレッドを作っておくことで、スレッド起動の重いコストを払わずに、ゴルーチンがブロックされた時、即座に他のゴルーチンを起動できるようになるというものがあります。
正しい内容：
この方式にはここには触れられていないメリットがあり、「スレッドプールにスレッドを作っておくことで、スレッド起動の重いコストを払わずに、ゴルーチンがブロックされた時、即座に他のゴルーチンを起動できるようになる」というものがあります。
その他コメント：

**Comment by ymotongpoo** [comment]
@hkdnet ご報告ありがとうございます。errataに登録しました。
