### ISSUE TITLE
p.218 訳注 されいます → されています

### ISSUE THREAD

**Issue by hkdnet** [oreilly-japan/concurrency-in-go-support#18]
ページ番号：p.218
セクション番号：補遺A
内容タイトル：訳注 されいます → されています
誤っている内容：
net/http/pprof という標準パッケージも提供されいます。
正しい内容：
net/http/pprof という標準パッケージも提供されています。
その他コメント：

**Comment by ymotongpoo** [comment]
@hkdnet 報告ありがとうございます。errataに登録しました。
