### ISSUE TITLE
カギ括弧閉じが無い

### ISSUE THREAD

**Issue by michilu** [oreilly-japan/concurrency-in-go-support#2]
ページ番号：31
セクション番号：2.3 訳注4
内容タイトル：カギ括弧閉じが無い
誤っている内容：「コードをうまく部品としてカプセル化しやすいような言語のモジュール機能や型システムなどを評価する言葉として使用しています。
正しい内容：
その他コメント：

**Comment by ymotongpoo** [comment]
@michilu ご報告ありがとうございます。errataに登録いたしました。

https://github.com/oreilly-japan/concurrency-in-go-support/wiki/errata#p31-23-%E8%84%9A%E6%B3%A84
