### ISSUE TITLE
p.147 体裁の乱れ。mobi/ePub版のみ

### ISSUE THREAD

**Issue by michilu** [oreilly-japan/concurrency-in-go-support#23]
ページ番号：147
セクション番号：4.12
内容タイトル：体裁の乱れ
誤っている内容：PDF版での丸数字箇条書き（mobi/ePub版では数字箇条書き）部分の、見出しと文の区切りが不明確で、改行とインデントがうまく表示されていないように見える
正しい内容：
その他コメント：mobi/ePub版のみ

**Comment by orj-takizawa** [comment]
ご指摘ありがとうございます。マークアップに問題がありましたので修正します。
