### ISSUE TITLE
p.152 全角ダッシュの対

### ISSUE THREAD

**Issue by michilu** [oreilly-japan/concurrency-in-go-support#24]
ページ番号：152
セクション番号：5.1
内容タイトル：全角ダッシュの対
誤っている内容：9行目「促します――おそらく」の全角ダッシュの対
正しい内容：
その他コメント：
慣習的に全角ダッシュは対で表記されると思います（本書でもこれまでそのような表記でした）が、この部分のみ対になる全角ダッシュがありませんでした。この部分のすぐ後にも全角ダッシュ表記が続くことから、読みにくくなっているように感じました。

**Comment by orj-takizawa** [comment]
ご指摘ありがとうございます。
ダッシュを使うのは文中の語なり文なりを補足する際、後に文をつなげる時と理解していて、補足の対象が文中にあり、後にもテキストが続く場合には後にもダッシュを付けてカッコのようにして区切りを入れると理解しています。ご指摘の箇所はそこで文が終わっているので、この場合、後のダッシュは必要ないと考えています。
