### ISSUE TITLE
p.177 この例のような → この例のように

### ISSUE THREAD

**Issue by michilu** [oreilly-japan/concurrency-in-go-support#26]
ページ番号：177
セクション番号：5.4
内容タイトル：誤字の疑い
誤っている内容：この例のような
正しい内容：この例のように
その他コメント：本文13行目。「この例のような」が「リクエスト」にかかっているように読めましたが、サンプルコード内の「リクエスト」そのものについて詳細に説明されているようには見えませんでした。「この例のように」の方が、「どのように『複製する』か」の部分をより強調するように思います。

**Comment by orj-takizawa** [comment]
ご指摘ありがとうございます。正誤表に追加してテキストも修正します。
