### ISSUE TITLE
p.181 割合 → 速度

### ISSUE THREAD

**Issue by michilu** [oreilly-japan/concurrency-in-go-support#27]
ページ番号：181
セクション番号：5.5
内容タイトル：誤字の疑い
誤っている内容：割合が 1トークン毎秒の例です。
正しい内容：速度が 1トークン毎秒の例です。
その他コメント：3行目。「割合」という語句は、ここのみに使われているようでした。後続の「次の例」では「速度が 0.5トークン毎秒の場合」とあります。

**Comment by orj-takizawa** [comment]
ありがとうございます。増刷時に統一したいと思います。
