### ISSUE TITLE
p.207 fib次の呼び出し

### ISSUE THREAD

**Issue by michilu** [oreilly-japan/concurrency-in-go-support#28]
ページ番号：207
セクション番号：6.1.1
内容タイトル：不自然な表記
誤っている内容：fib次の呼び出し
正しい内容：
その他コメント：箇条書き2行目。語句の入れ替わり、または脱字ではないかと思われます。

**Comment by orj-takizawa** [comment]
ご指摘の通り、この箇所に「の」の脱字がありました。正誤表に追加して修正します。ありがとうございます。
