### ISSUE TITLE
誤字脱字、その他間違いが疑われる箇所

### ISSUE THREAD

**Issue by yanolab** [oreilly-japan/concurrency-in-go-support#3]
下記、誤字脱字と原著が間違っているのか、意図していないような表記になっているところも指摘させていただきました。

ページ番号：P4
セクション番号：1.2
内容タイトル：誤字
誤っている内容：4行目後半「 実際に、サンプルプログラムをでも」
正しい内容： 「実際に、サンプルプログラムでも」
その他コメント：「を」が余計に入ってしまっているかと思われます。

ページ番号：P9
セクション番号：1.2.3
内容タイトル：サンプルプログラムが間違っている？
誤っている内容：
サンプルプログラム10行目
fmt.Printf("the value is %v.\n", value)
正しい内容：
fmt.Printf("the value is 0.")
その他コメント：
こちらはプログラムとしては間違っていませんが、P8のサンプルコードからコードが変わってしまっているので、if elseでの分岐の意味がなくなっているので、間違いかなと思われます。

ページ番号：P10
セクション番号：1.2.4
内容タイトル：誤字
誤っている内容：3行目中頃「また別の問題に取り組まければいけません。」
正しい内容： 「また別の問題に取り組まなければいけません。」
その他コメント：「な」が抜けてしまっています。

ページ番号：P52
セクション番号：3.2.2
内容タイトル：誤植
誤っている内容：② 生産者1秒スリープさせて
正しい内容：②生産者を1ナノ秒スリープさせて
その他コメント：②が示すコードはtime.Sleep(1)なので、ナノ秒かと思います。

ページ番号：P57
セクション番号：3.2.3
内容タイトル：誤字
誤っている内容：④ これはプログラムがstdoutへの書き込む前に終了してしまわない...
正しい内容：④これはプログラムがstdoutへ書き込む前に終了してしまわない...
または、④これはプログラムがstdoutへの書き込み前に終了してしまわない...
その他コメント：stdoutへの書き込むがおかしいと思われます。

ページ番号：P61
セクション番号：3.2.5
内容タイトル：原文が間違っている？
誤っている内容：本文4行目、「sync.Poolを使えばたった4KBのアロケーションで済みました。」
正しい内容： 「sync.Poolを使えばたった8KBのアロケーションで済みました。」
その他コメント：サンプルプログラムでは1Kのメモリを確保していて、実行結果に"8 calculators were created."とありますので、正しくは8KBかなと思います。

**Comment by ymotongpoo** [comment]
@yanolab ご報告ありがとうございます。すべて確認し、p.61のもの以外は間違いであるため、errataに登録しました。

p.61のものに関しては、表現がややこしいですが、「元々4KB確保していたところに、追加で4KBアロケーションしただけで済んだ」という内容として、現状のような内容となっています。ePub版、mobi版で表現を修正します。
