### ISSUE TITLE
p.219 ruuntime → runtime （PDF版のみ）

### ISSUE THREAD

**Issue by michilu** [oreilly-japan/concurrency-in-go-support#30]
ページ番号：219
セクション番号：A.4
内容タイトル：誤字
誤っている内容：ruuntime/traceパッケージ
正しい内容：runtime/traceパッケージ
その他コメント：下から2行目。PDF版のみ

**Comment by orj-takizawa** [comment]
ご指摘ありがとうございます。正誤表に追加して修正します。
