### ISSUE TITLE
送り仮名抜け お話しま → お話ししま

### ISSUE THREAD

**Issue by michilu** [oreilly-japan/concurrency-in-go-support#31]
ページ番号：
セクション番号：
内容タイトル：送り仮名抜け
誤っている内容：お話しま
正しい内容：お話ししま
その他コメント：
「お話しします。」が1箇所（p.105 4段落目2行目）ありましたので、送り仮名抜けとして挙げます。
「お話しま」6箇所
- [ ] 1. p.ix　序文　7行目
- [ ] 2. p.21　1.3　3行目
- [ ] 3. p.82　3.5　本文下から7行目
- [ ] 4. p.87　4章　2段落目6行目
- [ ] 5. p.111　4.6.2　本文下から3行目
- [ ] 6. p.160　5.2　16行目

**Comment by orj-takizawa** [comment]
ありがとうございます。増刷時に修正いたします。
