### ISSUE TITLE
誤字脱字など

### ISSUE THREAD

**Issue by tooru** [oreilly-japan/concurrency-in-go-support#32]
楽しく読まさせていただきました。誤字脱字と思われるものを見つけたので報告いたします。

ページ番号：p.9
セクション番号：1.2.3
内容タイトル：誤字
誤っている内容：コードでは、`var value int`となっているが、(1)の説明は「data変数」となっている。
正しい内容：p.8のから続いているので、コードの方の間違いで`var data int`でしょうか。
その他コメント：

ページ番号：p.76
セクション番号：3.3
内容タイトル：表3-2、語の揺れ？
誤っている内容：チャネルの状態の一番下「受信専用」
正しい内容：あるが他と合わせると「読み込み専用」ではないでしょうか？
その他コメント：

ページ番号：p.81
セクション番号：3.4
内容タイトル：ループの回数
誤っている内容：「ご覧のとおり、1000回の繰り返し」とあるが、正確には1001回。
正しい内容：上のコードの、`for i := 1000; i >= 0; i--`を`for i := 0; i < 1000; i++`とすれば本文に合わせられるかもしれません。コードを直すと実行結果の`c1Count:505` `c2Count:496`も直さないといけませんが。
その他コメント：

**Comment by ymotongpoo** [comment]
@tooru コメントありがとうございます。

> ページ番号：p.9
> セクション番号：1.2.3
> 内容タイトル：誤字
> 誤っている内容：コードでは、var value intとなっているが、(1)の説明は「data変数」となっている。
> 正しい内容：p.8のから続いているので、コードの方の間違いでvar data intでしょうか。
> その他コメント：

たしかにこちらは変数名は `value` ではなく `data` であるべきですね。

> ページ番号：p.76
> セクション番号：3.3
> 内容タイトル：表3-2、語の揺れ？
> 誤っている内容：チャネルの状態の一番下「受信専用」
> 正しい内容：あるが他と合わせると「読み込み専用」ではないでしょうか？
> その他コメント：

こちら、訳語揺れでした。

> ページ番号：p.81
> セクション番号：3.4
> 内容タイトル：ループの回数
> 誤っている内容：「ご覧のとおり、1000回の繰り返し」とあるが、正確には1001回。
> 正しい内容：上のコードの、for i := 1000; i >= 0; i--をfor i := 0; i < 1000; i++とすれば本文に合わせられるかもしれません。コードを直すと実行結果のc1Count:505 c2Count:496も直さないといけませんが。
> その他コメント：

こちらは脚注で対応します。

**Comment by ymotongpoo** [comment]
errataに反映しました。
