### ISSUE TITLE
p.28 epub版で論文タイトルが正しく表記されていない

### ISSUE THREAD

**Issue by yuyabu** [oreilly-japan/concurrency-in-go-support#33]
ページ番号：28
セクション番号：2.2
内容タイトル：誤字
誤っている内容：「Guarded commandsで
正しい内容：「Guarded commands, nondeterminacy and formal derivation of programs(ガード付きコ マンド、非決定性とプログラムの形式的導出、http://bit.ly/DijkstraGuarded)」で
その他コメント：pdf版とepub版に差分があります。Dijkstraの論文タイトル、リンクが正しく全て表示されていません。参考に該当部分のスクリーンショットを貼っておきます

pdf版
<img width="565" alt="image" src="https://user-images.githubusercontent.com/23971274/48301578-8c048780-e533-11e8-816b-933315e2609c.png">

kindle版
<img width="560" alt="image" src="https://user-images.githubusercontent.com/23971274/48301582-9757b300-e533-11e8-9faf-37d6551f3796.png">

**Comment by orj-takizawa** [comment]
ご指摘ありがとうございます。EPUBのビルドツールの癖が原因でした。お詫びして訂正いたします。
サイトのデータをアップデートしましたので、再ダウンロードしていただければ幸いです。
