### ISSUE TITLE
P.15 epub版でソースコードと文章の対応数字が間違っている

### ISSUE THREAD

**Issue by yuyabu** [oreilly-japan/concurrency-in-go-support#34]
ページ番号：15
セクション番号：1.2
内容タイトル：誤記
誤っている内容：

<img width="643" alt="image" src="https://user-images.githubusercontent.com/23971274/48301692-231e0f00-e535-11e8-999a-9a43d37fbf87.png">

正しい内容：

5,6,7と箇条書きになっている数字は1,2,3とするのが正しい

その他コメント：ibooksから該当部分をコピペしようとしたところ、数字部分がコピペできませんでした。

**Comment by orj-takizawa** [comment]
ご指摘ありがとうございます。EPUBのビルドツールの癖が原因でした。お詫びして訂正いたします。
サイトのデータをアップデートしましたので、再ダウンロードしていただければ幸いです。
