### ISSUE TITLE
p47.誤記

### ISSUE THREAD

**Issue by tooru** [oreilly-japan/concurrency-in-go-support#39]
ページ番号：p.47
セクション番号：3.1
内容タイトル：strcut->struct
誤っている内容：❷ 受信側のゴルーチンにメッセージを送信しています。`strcut{}`は空構造体と呼ばれるもので
正しい内容：`struct{}`
その他コメント：

**Comment by orj-takizawa** [comment]
ありがとうございます。ご指摘の通りです。正誤表に追加して、増刷時に修正いたします。
