### ISSUE TITLE
p.71 サンプルコードの出力結果の誤り

### ISSUE THREAD

**Issue by y0za** [oreilly-japan/concurrency-in-go-support#40]
ページ番号：p.71
セクション番号：3.3 チャネル(channel)
内容タイトル：p.71 サンプルコードの出力結果の誤り
誤っている内容：出力結果に`4 has begun`が含まれている
正しい内容：出力結果を変更するかサンプルコードのforの条件を変える
その他コメント：
該当のコードをThe Go Playgroundで実行したので貼っておきます。
https://play.golang.org/p/7PlLQY2VXCf

この内容は紙版の初版第1刷発行のもので確認しました。

**Comment by orj-takizawa** [comment]
ありがとうございます。ご指摘の通り、いずれかの方法で修正するか、何がしかの注釈が必要になりそうです。訳者さんと相談の上、修正したいと思います。

**Comment by orj-takizawa** [comment]
確認の結果、原著のEratta転記時のミスであることが判明しました。申し訳ございません。正誤表に追加して修正いたします。ありがとうございました。
