### ISSUE TITLE
p.15 誤植

### ISSUE THREAD

**Issue by cia-rana** [oreilly-japan/concurrency-in-go-support#41]
ページ番号：15
誤っている内容：①このプログラムが終わるように、試行回数に作為的な上限を**儲**けました。
正しい内容：①このプログラムが終わるように、試行回数に作為的な上限を**設**けました。

**Comment by orj-takizawa** [comment]
ご指摘ありがとうございます。正誤表に追加いたしました。また、今後の増刷時に修正いたします。
