### ISSUE TITLE
表3-1: PDF版とmobi/ePub版の差異

### ISSUE THREAD

**Issue by michilu** [oreilly-japan/concurrency-in-go-support#5]
ページ番号： 45
セクション番号： 3.1
内容タイトル： 表3-1: PDF版とmobi/ePub版の差異
誤っている内容： mobi/ePub版「表3-1」の左上から2列目3行目「A.436」
正しい内容： 7.436（PDF版より）
その他コメント：

**Comment by ymotongpoo** [comment]
@orj-takizawa 出版プロセスにおいてmobi版、ePub版にのみ差分が発生することがあるのでしょうか。

**Comment by ymotongpoo** [comment]
こちら修正されたためクローズします。
