### ISSUE TITLE
3.3 誤字の疑い

### ISSUE THREAD

**Issue by michilu** [oreilly-japan/concurrency-in-go-support#9]
ページ番号：66
セクション番号：3.3
内容タイトル：3.3 誤字の疑い
誤っている内容：後ほど、なぜその重要性を説明します。
正しい内容：後ほど、その重要性を説明します。
その他コメント：4行目

**Comment by ymotongpoo** [comment]
@michilu 報告ありがとうございます。errataに登録しました。
